baseURL = "https://astrology.ir"

theme = ["minimo"]

disqusShortname = ""
googleAnalytics = "G-RQL06NV6ED"

Paginate = 7
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "fa"

buildFuture=true

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js", "js/jquery-3.4.1.slim.min.js", "js/popper.min.js", "js/bootstrap.min.js", ]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "astrology.ir"
startYear = "2021"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideEntryMeta = ["page"] # boolean / array of sections
showReadingTime = true
showLastmod = true
taxonomyCloudShuffle = true
accentColor = "#0064a0"
hideMainMenu = false

[params.sidebar]
enable = true

[params.widgets]
header = ["breadcrumbs"]
homepage = ["recent_posts"]
sidebar = ["about","language","search","sidebar_menu","taxonomy_cloud"]
footer = ["social_menu"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
email = "irastrology@gmail.com"
facebook = "astrology.ir"
instagram = "ir_astrology"
twitter = "AstrologyIr"
telegram = "AstrologyIr"

[params.comments]
enable = false

# Isso: https://posativ.org/isso/
[params.comments.isso]
enable = false
scriptSrc = "" # "https://isso.example.com/js/embed.min.js"
dataAttrs = "" # "data-isso='https://isso.example.com' data-isso-require-author='true'"

[params.comments.staticman]
enable = true
apiEndpoint = "https://api.staticman.net/v2/entry"
maxDepth = 2
username = "astrology.ir"
repository = "minimo"

# Utterances: https://utteranc.es
[params.comments.utterances]
enable = false
issueTerm = "pathname" # pathname / url / title / og:title / <string>
label = ""
theme = "github-light"

[params.comments.utterances.github]
username = "astrology.ir"
repository = ""

[params.search]
client = "fuse" # algolia / fuse / lunr

[params.search.algolia]
appId = ""
indexName = ""
searchApiKey = ""

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
contentDir = "content/en"
lang = "en"
languagedirection = "ltr"
languageName = "English"
weight = 1
title = "Astrology"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""
[languages.en.params.info]
description = "Astrology research and data analysis, with a tendency to the Persian Astrology"
title404 = "Nothing's here!"

[languages.fa]
contentDir = "content/fa"
lang = "fa"
languagedirection = "rtl"
languageName = "پارسی"
weight = 2
title = "آسترولوژی"
[languages.fa.params.info]
description = "پژوهش و تحلیل داده‌ها در باب اختربینی با گرایش به سبک ایرانی"
title404 = "Nothing's here!"

